#!/bin/bash
set -e

case "$1" in
    'persistent')
        systemctl --user mask cachyos-gamescope-autologin.service
        pkexec /usr/lib/steamos/steam-set-session plasma.desktop;;
    'oneshot')
        systemctl --user unmask cachyos-gamescope-autologin.service
        pkexec /usr/lib/steamos/steam-set-session gamescope-session.desktop;;
    'gamescope')
        pkexec /usr/lib/steamos/steam-set-session gamescope-session.desktop
        pkexec /usr/bin/systemctl restart plasmalogin.service;;
    'plasma')
        pkexec /usr/lib/steamos/steam-set-session plasma.desktop
        steam -shutdown
        systemctl --user stop gamescope-session.target;;
    *)
        [[ -n "$1" ]] && echo -e "Unknown session '$1'\n"
        echo "Usage: $(basename "$0") <gamescope|plasma|persistent|oneshot>"
        exit 1;;
esac
