context.modules = [
    {   name = libpipewire-module-filter-chain
        flags = [ nofail ]
        args = {
            node.description = "Dynamics (Navi 31 HDMI/DP) Audio"
            media.name       = "Dynamics (Navi 31 HDMI/DP) Audio"
            filter.graph = {
                nodes = [
                    { type = ladspa name = comp_l plugin = dyson_compress_1403
                      label = dysonCompress
                      control = {
                          "Peak limit (dB)"        = -6
                          "Release time (s)"       = 0.3
                          "Fast compression ratio" = 0.4
                          "Compression ratio"      = 0.5
                      } }
                    { type = ladspa name = comp_r plugin = dyson_compress_1403
                      label = dysonCompress
                      control = {
                          "Peak limit (dB)"        = -6
                          "Release time (s)"       = 0.3
                          "Fast compression ratio" = 0.4
                          "Compression ratio"      = 0.5
                      } }
                    { type = ladspa name = limiter plugin = fast_lookahead_limiter_1913
                      label = fastLookaheadLimiter
                      control = {
                          "Input gain (dB)"  = 0
                          "Limit (dB)"       = -1
                          "Release time (s)" = 0.3
                      } }
                ]
                links = [
                    { output = "comp_l:Output" input = "limiter:Input 1" }
                    { output = "comp_r:Output" input = "limiter:Input 2" }
                ]
                inputs  = [ "comp_l:Input" "comp_r:Input" ]
                outputs = [ "limiter:Output 1" "limiter:Output 2" ]
            }
            capture.props = {
                node.name        = Dynamics-Navi
                node.description = "Dynamics (Navi 31 HDMI/DP) Audio"
                media.class      = Audio/Sink
                audio.channels   = 2
                audio.position   = [ FL FR ]
            }
            playback.props = {
                node.name          = Dynamics-Navi-Output
                node.passive       = true
                node.dont-fallback = true
                node.dont-move     = true
                audio.channels     = 2
                audio.position     = [ FL FR ]
                target.object      = alsa_output.pci-0000_03_00.1.hdmi-stereo
            }
        }
    }
]
