context.modules = [
    {   name = libpipewire-module-filter-chain
        flags = [ nofail ]
        args = {
            node.description = "Stereo Spatial (Matrix Spatialiser) HDMI"
            media.name       = "Stereo Spatial (Matrix Spatialiser) HDMI"
            filter.graph = {
                nodes = [
                    { type = ladspa name = matrix plugin = matrix_spatialiser_1422
                      label = matrixSpatialiser
                      control = { "Width" = 80 } }
                ]
                inputs  = [ "matrix:Input L" "matrix:Input R" ]
                outputs = [ "matrix:Output L" "matrix:Output R" ]
            }
            capture.props = {
                node.name        = Matrix-Spatialiser-HDMI
                node.description = "Stereo Spatial (Matrix Spatialiser) HDMI"
                media.class      = Audio/Sink
                audio.channels   = 2
                audio.position   = [ FL FR ]
            }
            playback.props = {
                node.name      = Matrix-Spatialiser-HDMI-Output
                node.passive   = true
                audio.channels = 2
                audio.position = [ FL FR ]
                target.object  = alsa_output.pci-0000_03_00.1.hdmi-stereo
            }
        }
    }
]
